# Server Configuration
server:
  port: 8080

# Eureka Configuration
eureka:
  instance:
    status-page-url-path: ${server.contextPath:}/info
    health-check-url-path: ${server.contextPath:}/health
    hostname: ${reportportal.eureka.instance.hostname:localhost}
    metadata-map:
      extension: sbm

  client:
    serviceUrl:
      defaultZone: http://${reportportal.eureka.hostname:localhost}:8761/eureka/

# MongoDB configuration
rp:
  mongo:
    host: ${reportportal.mongo.host:localhost}
    port: 27017
    dbName: reportportal
#        user: user
#        password: 1q2w3e
    connectionsPerHost: 1000
    threadsAllowedToBlockForConnectionMultiplier: 1000
    connectTimeout: 20000
    socketTimeout: 60000
    maxWaitTime: 120000
    autoConnectRetry: true
    socketKeepAlive: true
    slaveOk: true
    writeTimeout: 0
    writeNumber: 1
    writeFsync: false
  cache:
      project:
        size: 1000
        expiration: 1
        info: 10
      ticket:
        size: 10000
        expiration: 5
      user:
        size: 1000
        expiration: 60


## OAUTH PRIVATE-PUBLIC keypair for JIRA integration
oauth:
  certificate:
    store: oauth-keystore.jks

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags:
          - urlprefix-${server.context-path:}/sbm opts strip=/sbm
          - traefik.frontend.rule=PathPrefixStrip:${server.context-path:/}
          - statusPageUrlPath=${server.contextPath:}/info
          - healthCheckUrlPath=${server.contextPath:}/health
          - extension:sbm
        healthCheckPath: ${server.contextPath:}/health
        ip-address: 10.200.10.1
        prefer-ip-address: true
        register: false
      enabled: false

## Consul as service registry
---
spring:
  profiles: eureka
  cloud:
    consul:
      enabled: false
      discovery:
        register: false

## Consul as service registry
---
spring:
  profiles: consul
  cloud:
    consul:
      enabled: true
      discovery:
        register: true
eureka:
  client:
    register-with-eureka: false
    enabled: false
---
